### ISSUE TITLE
Attribute name length limitation?

### ISSUE THREAD

**Issue by FIMTooler** [lithnet/resourcemanagement-powershell#34]
Is there a character limit on the system name of an attribute?

I have both a 25 and 29 character length name for 2 attributes that are both booleans.  When I search resources (with AttributesToGet, Unconstrained, or ExpectedObjectType), the attribute with the 29 character length is not returned, yet the 25 character length property is returned.

Using xPath to filter on the 29 character length attribute returns the correct number of objects with true\false values, yet the property itself is never listed.

Using Export-FIMConfig, the 29 character length attribute is returned.

Since it's not listed on the returned object, it cannot be modified.

**Comment by ryannewington** [comment]
I'm not sure I can explain this one. There isn't a limit on the attribute length. I've got plenty of > 25 char attributes in my environment

![image](https://user-images.githubusercontent.com/17229877/115940216-021ebe00-a4e4-11eb-9b98-eb781e96819f.png)

Can you give me some more specific steps to reproduce?

Is it a new schema attribute? You may need to restart the FIM service and restart PowerShell session in order to see newly created attributes, but that's the only reason I can think of for it not being seen. We do cache the schema to avoid expensive round-trips, and you have to invoke `Update-ResourceManagementClientSchema` to force a refresh.

**Comment by FIMTooler** [comment]
It probably is cached from existing powershell session as I usually disconnect from rdp keeping all the apps open.


I'll be able to verify in a couple of hours, but that seems to be the most likely scenario.

Thanks for the quick follow-up!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryannewington** [comment]
Ok great. Let me know how you go.

**Comment by FIMTooler** [comment]
It was the schema refresh.  Once that was done it worked.  Thanks again!
